#cloud-config
package_update: true
packages:
  - curl
  - jq
  - certbot
  - socat
  - docker.io
  - docker-compose

write_files:
  - path: /opt/shadowsocks/docker-compose.yml
    permissions: '0644'
    content: |
      __DOCKER_COMPOSE__

runcmd:
  - if [ "__MODE__" = "tls" ]; then
      certbot certonly --standalone --non-interactive --agree-tos -m __EMAIL__ -d __SUBDOMAIN__.__DOMAIN__;
    fi
  - docker-compose -f /opt/shadowsocks/docker-compose.yml up -d
