#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
  - certbot

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - |
    while ! docker info >/dev/null 2>&1; do
      echo "Docker not ready yet... retrying in 15s"
      sleep 15
    done
    certbot certonly --standalone --non-interactive --agree-tos \
      -m {{EMAIL}} \
      -d {{FQDN}}
    if [ "{{MODE}}" = "tls" ]; then
      echo "Starting Shadowsocks server with TLS..."
      docker run -d --name shadowsocks --restart unless-stopped \
        -p 443:443 \
        -v /etc/letsencrypt:/etc/letsencrypt:ro \
        teddysun/shadowsocks-rust:latest \
        ssserver -s 0.0.0.0:443 \
                 -m chacha20-ietf-poly1305 \
                 -k "{{PASSWORD}}" \
                 --plugin v2ray-plugin \
                 --plugin-opts "server;tls;host={{FQDN}};cert=/etc/letsencrypt/live/{{FQDN}}/fullchain.pem;key=/etc/letsencrypt/live/{{FQDN}}/privkey.pem"
    else
      echo "Starting Shadowsocks server with tcp-udp..."
      docker run -d --name shadowsocks --restart unless-stopped \
        -p 443:443/tcp \
        -p 443:443/udp \
        teddysun/shadowsocks-rust:latest \
        ssserver -s 0.0.0.0:443 \
                 -m chacha20-ietf-poly1305 \
                 -k "{{PASSWORD}}"
    fi
