name: Deploy Shadowsocks

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Base domain (example.com)"
        required: true
      subdomain:
        description: "Subdomain (e.g. ss)"
        required: true
      email:
        description: "Email for Let's Encrypt"
        required: true
      password:
        description: "Shadowsocks password"
        required: true
      mode:
        description: "tls or tcp-udp"
        required: true
        default: "tls"
      region:
        description: "DigitalOcean region (e.g., nyc1, sfo3, ams3)"
        required: true
        default: "sfo3"
      size:
        description: "Droplet size slug (e.g., s-1vcpu-512mb-10gb)"
        required: true
        default: "s-1vcpu-512mb-10gb"
      image:
        description: "Droplet image slug (e.g., ubuntu-22-04-x64)"
        required: true
        default: "ubuntu-22-04-x64"
      hostname:
        description: "Droplet hostname"
        required: true
        default: "ss"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/deploy-shadowsocks
        with:
          domain: ${{ github.event.inputs.domain }}
          subdomain: ${{ github.event.inputs.subdomain }}
          email: ${{ github.event.inputs.email }}
          password: ${{ github.event.inputs.password }}
          mode: ${{ github.event.inputs.mode }}
          do_token: ${{ secrets.DO_API_TOKEN }}
          ssh_key: ${{ secrets.DO_SSH_KEY }}
          region: ${{ github.event.inputs.region }}
          size: ${{ github.event.inputs.size }}
          image: ${{ github.event.inputs.image }}
          hostname: ${{ github.event.inputs.hostname }}